### ISSUE TITLE
[Bug] Proxy extraction broken due to missing sections internal property

### ISSUE THREAD

**Issue by liamcannon** [MrClock8163/Arma3ObjectBuilder#61]
### Add-on version

Release

### Description

Imported a3 character -> selected weapon proxy -> changed weapon proxy to p3d -> clicked extract proxy -> encountered error.

### Steps to reproduce

Attempt to extract proxy for provided P3D (mpl in discord dms)

### Stack trace

```shell
Traceback (most recent call last):
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\ui\tool_proxies.py", line 138, in execute
    lod_objects = import_p3d.read_file(self, context, file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\io\import_p3d.py", line 460, in read_file
    lod_objects.append(process_lod(operator, logger, lod, materials, materials_lookup, categories, lod_links[i]))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\io\import_p3d.py", line 365, in process_lod
    process_materials(operator, mesh, bm, lod, materials, materials_lookup)
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\io\import_p3d.py", line 138, in process_materials
    if operator.sections == 'PRESERVE':
       ^^^^^^^^^^^^^^^^^
  File "F:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\bpy_types.py", line 939, in __getattribute__
    return super().__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'A3OB_OT_proxy_extract' object has no attribute 'sections'
Traceback (most recent call last):
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\ui\tool_proxies.py", line 147, in execute
    imported_object = lod_objects[0]
                      ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'lod_objects' where it is not associated with a value
Error: 'A3OB_OT_proxy_extract' object has no attribute 'sections' (check the system console)
Error: Python: Traceback (most recent call last):
  File "C:\Users\Liam Cannon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Arma3ObjectBuilder\ui\tool_proxies.py", line 147, in execute
    imported_object = lod_objects[0]
                      ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'lod_objects' where it is not associated with a value
```

**Comment by MrClock8163** [comment]
Verified the issue.
Turns out this is the actual error that's causing the issue:

```py
AttributeError: 'A3OB_OT_proxy_extract' object has no attribute 'sections'
```

Apparently I forgot to add the latest P3D import option to the Extract Proxy operator.
